### ISSUE TITLE
this base image not working？

### ISSUE THREAD

**Issue by xiaods** [lloydbenson/docker-centos-7-sshd#1]
i read the README, found the description mentioned as the image as base image, how can i use it ?i set  root passwd, but i can't login to container.

**Comment by lloydbenson** [comment]
How did you set the root password?  Can you send me an example of what you tried (obviously just replace the password with some other word).  I can try to reproduce your scenario.  It is likely that I just need to improve the documentation.

**Comment by xiaods** [comment]
@lloydbenson i get thing done. thanks. 

i just use the README's docker run, and docker logs, but not found the logs.

**Comment by lloydbenson** [comment]
I see, yeah it might be a nice enhancement to have it give the ssh logs on stdout, wouldn't be that much work.  I'd take a PR (likely just a sshd config copy setting).  But sounds like you got it working.

**Comment by lloydbenson** [comment]
also I should mention this image really has systemd as the init not sshd.  So if you really wanted logs you'd have to map the log dir to see them.
